version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quasar_db_container
    restart: unless-stopped
    env_file:
      - ../.env  # Load environment variables from .env
    ports:
      - "5432:5432"
    volumes:
      - quasar_db_data:/var/lib/postgresql/data

volumes:
  quasar_db_data:
